version: '3'

volumes:
  cache:
    driver: local
  db-data:
    driver: local

services:
  app:
    build:
      context: server/
    container_name: auth
    depends_on:
      - db
      - redis
    env_file:
      - server/.env
    ports:
      - '9090:9090'

  db:
    container_name: postgres
    image: postgres:15.1-alpine
    environment:
      - POSTGRES_USER=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ./src/main/resources/script:/docker-entrypoint-init.db.d
      - db-data:/var/lib/postgresql/data

  redis:
    container_name: redis
    image: redis:7.2-rc-alpine
    restart: always
    ports:
      - '6380:6380'
    command: redis-server --requirepass $${REDIS_PASSWORD}
    volumes:
      - cache:/data
