DB_IP: 127.0.0.1
DB_PORT: 5432
DB_DATABASE_NAME: store
DB_SCHEMA: public

logging:
  level:
    org:
      springframework:
        data:
          r2dbc=DEBUG:


  server:
    address: 192.168.0.107
    port: 8080

spring:

#    url: jdbc:postgresql://localhost:5432/store
#    username: admin
#    password: 52670

  r2dbc:
    url: r2dbc:postgresql://${POSTGRES_HOST}:5432/${POSTGRES_DB}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
  


  config:
    import: optional:file:store.env[.properties]
    cache:
      type: redis
      cache-names: redis-cache


  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

  profiles:
    active: dev

  data:
    redis:
      host: ${REDIS_HOST}
      port: 6379
      username: ${REDIS_USERNAME}
      password: ${REDIS_PASSWORD}

  sql:
    init:
      platform: postgres


  jpa:
    repositories:
    enabled: false
    bootstrap-mode: default

#  r2dbc:
#    repositories:
#       enabled: true
#    ldap:
#       repositories:
#       enabled: false
#    r2dbc:
#       url: r2dbc:postgresql://${POSTGRES_HOST}:5432/${POSTGRES_DB}
#       username: ${POSTGRES_USERNAME}
#       password: ${POSTGRES_PASSWORD}
#       pool:
#         enabled: true
#         initial-size: 10
#         max-idle-time: 1m
#         max-size: 30

#  datasource:
#    jdbc-url: jdbc:postgresql://${POSTGRES_HOST}:5432/${POSTGRES_DB}
#    username: ${POSTGRES_USERNAME}
#    password: ${POSTGRES_PASSWORD}
#    driver-class-name: org.postgresql.Driver

minio:
  bucket: ${MINIO_BUCKET}
  url: ${MINIO_URL}
  accessKey: ${MINIO_ACCESS_KEY}
  secretKey: ${MINIO_SECRET_KEY}
