version: '3.7'

services:
  elasticsearch:
    image: elasticsearch:7.16.1
    container_name: elasticsearch
    ports:
      - 9200:9200
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/datafile
    environment:
      - xpack.monitoring.enabled=true
      - xpack.watcher.enabled=false
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
    networks:
      - elk
    restart: always

  kibana:
    image: kibana:7.16.1
    container_name: kibana
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
    environment:
      - ELASTICSEARCH_URL=http://localhost:9200
    networks:
      - elk

  webapp:
    image: ${DOCKER_REGISTRY-}webapp
    container_name: webapp
    build:
      context: /mnt/c/Users/Shved/Documents/Projects/Employee-Management-Portal/WebAPI/
      dockerfile: src/WebAPI.Presentation/Dockerfile
    environment:
      - "UseInMemoryDatabase=false"
      - "ConnectionStrings__DefaultConnection=Data Source=(local);Initial Catalog=EmployeeDB;Persist Security Info=false;Integrated Security=True;MultipleActiveResultSets=True;"
      - "IdentityServer__Key__Type=Development"
      - "ASPNETCORE_Kestrel__Certificates__Default__Password=Your_password123"
      - "ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx"
    volumes:
      - ~/.aspnet/https:/https:ro
    ports:
      - 5000:5000
      - 5001:5001
    depends_on:
      - database
    restart: on-failure

  database:
    image: "mcr.microsoft.com/mssql/server"
    container_name: database
    environment:
      - "SA_PASSWORD=Your_password123"
      - "ACCEPT_EULA=Y"
    restart: always

networks:
  elk:
    driver: bridge

volumes:
  elasticsearch-data: {}
