// <auto-generated />

using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using WebAPI.DataAccess.MsSql.Persistence.Context;

namespace WebAPI.DataAccess.MsSql.Migrations
{
    [DbContext(typeof(AppDbContext))]
    internal class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.7")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WebAPI.Entities.Models.Department", b =>
            {
                b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uniqueidentifier");

                b.Property<string>("Name").HasColumnType("nvarchar(max)");

                b.HasKey("Id");

                b.ToTable("Departments");
            });

            modelBuilder.Entity("WebAPI.Entities.Models.Employee", b =>
            {
                b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uniqueidentifier");

                b.Property<DateTime>("DateOfJoining").HasColumnType("datetime2");

                b.Property<string>("Department").HasColumnType("nvarchar(max)");

                b.Property<string>("Name").HasColumnType("nvarchar(max)");

                b.Property<string>("PhotoFileName").HasColumnType("nvarchar(max)");

                b.HasKey("Id");

                b.ToTable("Employees");
            });
#pragma warning restore 612, 618
        }
    }
}