server:
  port: 9090

spring:
  config:
    import: optional:file:.env[.properties]
    cache:
      type: redis
      cache-names: redis-cache

  data:
    redis:
      host: ${REDIS_HOST}
      port: 6379
      username: ${REDIS_USERNAME}
      password: ${REDIS_PASSWORD}

  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:5432/${POSTGRES_DATABASE}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

  sql:
    init:
      platform: postgres

  spring.mail:
    host: smtp.gmail.com
    port: 465
    protocol: smtp
    username: xyz@gmail.com
    password: abc
    test-connection: true
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.starttls.required: true
      mail.smtp.socketFactory.class: javax.net.ssl.SSLSocketFactory
      mail.debug: true

security:
  jwt:
    expiration:
      secret: ${JWT_SECRET}
      access-token:  15 # 15 min
      refresh-token: 1440 # a day
