server:
  port: 9090

spring:
  config:
    import: optional:file:.env[.properties]
    cache:
      type: redis
      cache-names: redis-cache

  profiles:
    active: dev

  mail:
    host: smtp.gmail.com
    username: ${EMAIL_ADDRESS}
    password: ${EMAIL_KEY}
    port: 587
    protocol: smtp
    default-encoding: UTF-8
  #    properties:
  #      mail: default-encoding=UTF-8
  #      mail.smtp.auth: true
  #      mail.smtp.starttls.enable: true
  #      mail.smtp.starttls.required: false
  #      mail.smtp.socketFactory.class: javax.net.ssl.SSLSocketFactory
  #      mail.debug: true

  #    properties:
  #      mail.smtp:
  #        ssl.enable: true
  #        debug: true
  #        auth: true
  #        timeout: 5000
  #        write timeout: 5000
  #        connection timeout: 5000
  #      test-connection: false

  data:
    redis:
      host: ${REDIS_HOST}
      port: 6379
      username: ${REDIS_USERNAME}
      password: ${REDIS_PASSWORD}

  datasource:
    jdbc-url: jdbc:postgresql://${POSTGRES_HOST}:5432/${POSTGRES_DB}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

  sql:
    init:
      platform: postgres

security:
  jwt:
    expiration:
      secret: ${JWT_SECRET}
      expireAccessToken: 15 # 15 min
      expireRefreshToken: 43200 # a month

springdoc:
  override-with-generic-response: false
